# Numpy

In [25]:
!pip install numpy --upgrade --quiet

In [26]:
import numpy as np

In [28]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [29]:
x[0]

1

In [32]:
(x * y)

array([ 4, 10, 18])

In [31]:
(x * y).sum()

32

In [33]:
np.dot(x,y)

32

# 2,3D Array

In [40]:
arr1 = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
arr1.shape

(5, 3)

In [42]:
arr1[0,1]

67

In [41]:
arr2 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])
arr2.shape

(2, 2, 3)

In [43]:
arr2[1,1,2]

19.5

# Matrix Multiplication

In [53]:
weights = np.array([0,0,-1])

In [62]:
x = arr1 @ weights
x

array([-43, -64, -58, -37, -70])

In [73]:
x = x.reshape(5,1)
x

array([[-43],
       [-64],
       [-58],
       [-37],
       [-70]])

In [70]:
y = np.array([1,2,3,4,5])
y = y.reshape(5,1)
y

array([[1],
       [2],
       [3],
       [4],
       [5]])

# Concatenate

In [76]:
combined = np.concatenate((x,y),axis=0)
combined

array([[-43],
       [-64],
       [-58],
       [-37],
       [-70],
       [  1],
       [  2],
       [  3],
       [  4],
       [  5]])

In [77]:
combined_x = np.concatenate((x,y),axis=1)
combined_x

array([[-43,   1],
       [-64,   2],
       [-58,   3],
       [-37,   4],
       [-70,   5]])

# Numpy Arithmetic

In [80]:
arr3 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [81]:
arr4 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [82]:
arr3 + 2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11,  3,  4,  5]])

In [83]:
arr3 * arr4

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [87]:
arr_y = np.array([[1],[2],[3]])
arr_y

array([[1],
       [2],
       [3]])

In [88]:
arr_x = np.array([1,2,3])
arr_x

array([1, 2, 3])

In [89]:
arr_y + arr_x

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

# Array comparison

In [92]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [93]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [95]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

In [94]:
(arr1 == arr2).sum()

3

# Array Slice

In [96]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [97]:
arr3[1:]

array([[[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [98]:
arr3[1:, 0:1]

array([[[15., 16., 17., 21.]],

       [[98., 32., 81., 23.]]])

In [99]:
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

# Other numpy array creation

In [100]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [101]:
np.ones([2,2,2])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [110]:
np.random.rand(2,2)

array([[0.88680742, 0.90455731],
       [0.9981717 , 0.89355283]])

In [111]:
np.full([2, 3], 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [120]:
np.arange(10, 30, 3)

array([10, 13, 16, 19, 22, 25, 28])